name: oneofus_common
description: Core data models and cryptography for the ONE-OF-US.NET phone app.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  cryptography: ^2.7.0
  jwk: ^0.2.3
  convert: ^3.1.1
  collection: ^1.18.0
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
