name: oneofus_common
description: Core data models, cryptography, and I/O for the ONE-OF-US.NET protocol.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  cryptography: ^2.7.0
  jwk: ^0.2.3
  convert: ^3.1.1
  collection: ^1.18.0
  intl: ^0.20.1
  cloud_firestore: ^6.0.0
  firebase_core: ^4.0.0
  cloud_functions: ^6.0.0
  http: ^1.2.2
  google_fonts: ^6.3.2
  qr_flutter: ^4.1.0

dev_dependencies:
  fake_cloud_firestore: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
